In [16]:
import pandas as pd

In [17]:
brewery_apilist_df = pd.read_csv('brewery_list.csv') 
brewery_apilist_df.head()

,Unnamed: 0,id,name,brewery_type,street,address_2,address_3,city,state,county_province,postal_code,country,longitude,latitude,phone,website_url,updated_at,created_at
0,0,10-56-brewing-company-knox,10-56 Brewing Company,micro,400 Brown Cir,NaN,NaN,Knox,Indiana,NaN,46534,United States,-86.627954,41.289715,6308165790,NaN,2023-02-21T01:41:59.300Z,2023-02-21T01:41:59.300Z
1,1,10-barrel-brewing-co-bend-1,10 Barrel Brewing Co,large,62970 18th St,NaN,NaN,Bend,Oregon,NaN,97701-9847,United States,-121.281706,44.086835,5415851007,http://www.10barrel.com,2023-02-21T01:41:59.300Z,2023-02-21T01:41:59.300Z
2,2,10-barrel-brewing-co-bend-2,10 Barrel Brewing Co,large,1135 NW Galveston Ave Ste B,NaN,NaN,Bend,Oregon,NaN,97703-2465,United States,-121.328802,44.057565,5415851007,NaN,2023-02-21T01:41:59.300Z,2023-02-21T01:41:59.300Z
3,3,10-barrel-brewing-co-bend-pub-bend,10 Barrel Brewing Co - Bend Pub,large,62950 NE 18th St,NaN,NaN,Bend,Oregon,NaN,97701,United States,-121.280954,44.091211,5415851007,NaN,2023-02-21T01:41:59.300Z,2023-02-21T01:41:59.300Z
4,4,10-barrel-brewing-co-boise-boise,10 Barrel Brewing Co - Boise,large,826 W Bannock St,NaN,NaN,Boise,Idaho,NaN,83702-5857,United States,-116.202929,43.618516,2083445870,http://www.10barrel.com,2023-02-21T01:41:59.300Z,2023-02-21T01:41:59.300Z

In [18]:
brewery_apilist_df = brewery_apilist_df.drop(columns=['Unnamed: 0', 'updated_at','created_at','id'])
#brewery_apilist_df.columns

In [19]:
brewery_apilist_df= brewery_apilist_df.rename(columns={"name": "brewery_name"})
brewery_apilist_df.columns

Index(['brewery_name', 'brewery_type', 'street', 'address_2', 'address_3',
       'city', 'state', 'county_province', 'postal_code', 'country',
       'longitude', 'latitude', 'phone', 'website_url'],
      dtype='object')

In [20]:
brewery_untapped_macros_df = pd.read_csv('untapped_macros.csv') 
brewery_untapped_macros_df = brewery_untapped_macros_df.drop(columns=['Unnamed: 0'])

In [23]:
brewery_untapped_macros_df

,brewery_name,brewery_location,brewery_type,number_beers,brewery_ratings
0,Founders Brewing Co.,"Grand Rapids, MI United States",Macro Brewery,"964 Beers 7,168,191 Ratings",(3.962)
1,Wicked Weed Brewing,"Asheville, NC United States",Macro Brewery,"747 Beers 1,804,525 Ratings",(3.919)
2,Avery Brewing Co.,"Boulder, CO United States",Macro Brewery,"532 Beers 2,239,783 Ratings",(3.891)
3,Funky Buddha Brewery,"Oakland Park, FL United States",Macro Brewery,"1,135 Beers 832,534 Ratings",(3.891)
4,Goose Island Beer Co.,"Chicago, IL United States",Macro Brewery,"1,375 Beers 5,591,927 Ratings",(3.885)
5,AC Golden Brewing Co.,"Golden, CO United States",Macro Brewery,"104 Beers 16,498 Ratings",(3.867)
6,Bell's Brewery,"Comstock, MI United States",Macro Brewery,"675 Beers 4,523,588 Ratings",(3.849)
7,Lagunitas Brewing Company,"Petaluma, CA United States",Macro Brewery,"780 Beers 5,463,102 Ratings",(3.81)
8,Not Your Father’s,"Wauconda, IL United States",Macro Brewery,"90 Beers 375,323 Ratings",(3.808)
9,Terrapin Beer Co.,"Athens, GA United States",Macro Brewery,"545 Beers 1,605,734 Ratings",(3.746)
10,Elysian Brewing Company,"Seattle, WA United States",Macro Brewery,"779 Beers 1,501,927 Ratings",(3.74)
11,Appalachian Mountain Brewery,"Boone, NC United States",Macro Brewery,"331 Beers 165,831 Ratings",(3.732)
12,Guinness Open Gate Brewery,"Halethorpe, MD United States",Macro Brewery,"319 Beers 173,574 Ratings",(3.726)
13,Platform Beer Company,"Cleveland, OH United States",Macro Brewery,"1,249 Beers 672,583 Ratings",(3.724)
14,Winding Path Brewing Co.,"Dallastown, PA United States",Macro Brewery,"40 Beers 42,635 Ratings",(3.719)
15,Karbach Brewing Co.,"Houston, TX United States",Macro Brewery,"193 Beers 645,846 Ratings",(3.71)
16,Secret Llama,"Lakeland, FL United States",Macro Brewery,"17 Beers 10,507 Ratings",(3.7)
17,10 Barrel Brewing Co.,"Bend, OR United States",Macro Brewery,"1,584 Beers 740,533 Ratings",(3.663)
18,Golden Road Brewing,"Los Angeles, CA United States",Macro Brewery,"824 Beers 818,194 Ratings",(3.659)
19,Four Peaks Brewing Company,"Tempe, AZ United States",Macro Brewery,"379 Beers 369,267 Ratings",(3.655)
20,Revolver Brewing,"Granbury, TX United States",Macro Brewery,"141 Beers 188,922 Ratings",(3.643)
21,Veza Sur Brewing Co.,"Miami, FL United States",Macro Brewery,"97 Beers 46,259 Ratings",(3.633)
22,New Belgium Brewing Company,"Fort Collins, CO United States",Macro Brewery,"614 Beers 6,146,424 Ratings",(3.632)
23,Wynwood Brewing Company,"Miami, FL United States",Macro Brewery,"473 Beers 95,653 Ratings",(3.624)
24,Simply Spiked,"Milwaukee, WI United States",Macro Brewery,"8 Beers 7,062 Ratings",(3.623)
25,Breckenridge Brewery,"Littleton, CO United States",Macro Brewery,"823 Beers 1,444,405 Ratings",(3.622)
26,Devils Backbone Brewing Company,"Roseland, VA United States",Macro Brewery,"723 Beers 748,386 Ratings",(3.585)
27,Widmer Brothers Brewing,"Portland, OR United States",Macro Brewery,"553 Beers 596,317 Ratings",(3.528)
28,Kona Brewing Company,"Kailua Kona, HI United States",Macro Brewery,"170 Beers 1,752,057 Ratings",(3.524)
29,Anchor Brewing Company,"San Francisco, CA United States",Macro Brewery,"327 Beers 1,370,195 Ratings",(3.523)
30,Four Sixes Grit & Glory,United States,Macro Brewery,"5 Beers 3,486 Ratings",(3.521)
31,Blue Point Brewing Company,"Patchogue, NY United States",Macro Brewery,"162 Beers 699,469 Ratings",(3.521)
32,Kombrewcha Hard Kombucha,"Brooklyn, NY United States",Macro Brewery,"6 Beers 2,846 Ratings",(3.518)
33,PRESS Premium Alcohol Seltzer,"Milwaukee, WI United States",Macro Brewery,"10 Beers 12,868 Ratings",(3.502)
34,Cisco Brewers,"Nantucket Island, MA United States",Macro Brewery,"294 Beers 268,650 Ratings",(3.472)
35,Henry's Hard Soda,"Milwaukee, WI United States",Macro Brewery,"7 Beers 58,910 Ratings",(3.429)
36,Jacob Leinenkugel Brewing Company,"Chippewa Falls, WI United States",Macro Brewery,"302 Beers 1,732,478 Ratings",(3.413)
37,Blue Moon Brewing Company,"Denver, CO United States",Macro Brewery,"609 Beers 1,585,877 Ratings",(3.39)
38,Vibez,"Alexandria, VA United States",Macro Brewery,"19 Beers 2,199 Ratings",(3.378)
39,Jack Daniel's Beverage Co.,"Louisville, KY United States",Macro Brewery,"12 Beers 13,125 Ratings",(3.358)
40,Vizzy Hard Seltzer,"Memphis, TN United States",Macro Brewery,"20 Beers 36,813 Ratings",(3.348)
41,Genesee Brewing Company,"Rochester, NY United States",Macro Brewery,"313 Beers 243,246 Ratings",(3.334)
42,Malibu Splash,"New York, NY United States",Macro Brewery,"5 Beers 3,879 Ratings",(3.325)
43,Two Lane Brewing,"Daleville, VA United States",Macro Brewery,"5 Beers 4,195 Ratings",(3.323)
44,Bacardi,"Coral Gables, FL United States",Macro Brewery,"22 Beers 10,749 Ratings",(3.272)
45,Shock Top Brewing Co.,"St Louis, MO United States",Macro Brewery,"47 Beers 718,227 Ratings",(3.259)
46,Margaritaville Brewing Co.,"St. Louis, MO United States",Macro Brewery,"15 Beers 163,691 Ratings",(3.224)
47,Omission Brewing,"Portland, OR United States",Macro Brewery,"22 Beers 142,363 Ratings",(3.216)
48,Redd's Brewing Company,"Milwaukee, WI United States",Macro Brewery,"29 Beers 185,782 Ratings",(3.194)
49,Boathouse Beverage Co.,"Norwalk, CT United States",Macro Brewery,"9 Beers 34,913 Ratings",(3.143)

In [24]:
all_breweries_merged_df = pd.merge(brewery_untapped_macros_df, brewery_apilist_df, on=('brewery_name','brewery_type'),how='outer')

In [25]:
all_breweries_merged_df

,brewery_name,brewery_location,brewery_type,number_beers,brewery_ratings,street,address_2,address_3,city,state,county_province,postal_code,country,longitude,latitude,phone,website_url
0,Founders Brewing Co.,"Grand Rapids, MI United States",Macro Brewery,"964 Beers 7,168,191 Ratings",(3.962),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Wicked Weed Brewing,"Asheville, NC United States",Macro Brewery,"747 Beers 1,804,525 Ratings",(3.919),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Avery Brewing Co.,"Boulder, CO United States",Macro Brewery,"532 Beers 2,239,783 Ratings",(3.891),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Funky Buddha Brewery,"Oakland Park, FL United States",Macro Brewery,"1,135 Beers 832,534 Ratings",(3.891),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Goose Island Beer Co.,"Chicago, IL United States",Macro Brewery,"1,375 Beers 5,591,927 Ratings",(3.885),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8645,Able Ebenezer Brewing Company,NaN,micro,NaN,NaN,31 Columbia Cir,NaN,NaN,Merrimack,New Hampshire,NaN,03054-4161,United States,-71.493705,42.851742,8442232253,http://www.ableebenezer.com
8646,Able Ebenezer Brewing Company,NaN,micro,NaN,NaN,31 Columbia Cir,NaN,NaN,Merrimack,New Hampshire,NaN,03054-4161,United States,-71.493705,42.851742,8442232253,http://www.ableebenezer.com
8647,Able Ebenezer Brewing Company,NaN,micro,NaN,NaN,31 Columbia Cir,NaN,NaN,Merrimack,New Hampshire,NaN,03054-4161,United States,-71.493705,42.851742,8442232253,http://www.ableebenezer.com
8648,Able Ebenezer Brewing Company,NaN,micro,NaN,NaN,31 Columbia Cir,NaN,NaN,Merrimack,New Hampshire,NaN,03054-4161,United States,-71.493705,42.851742,8442232253,http://www.ableebenezer.com
8649,Able Ebenezer Brewing Company,NaN,micro,NaN,NaN,31 Columbia Cir,NaN,NaN,Merrimack,New Hampshire,NaN,03054-4161,United States,-71.493705,42.851742,8442232253,http://www.ableebenezer.com

In [42]:
cols_to_use = all_breweries_merged_df.columns.difference(brewery_untapped_regional_df.columns)
cols_to_use

Index(['address_2', 'address_3', 'brewery_location_x', 'brewery_location_y',
       'brewery_name_x', 'brewery_name_y', 'brewery_ratings_x',
       'brewery_ratings_y', 'brewery_type_x', 'brewery_type_y', 'city',
       'country', 'county_province', 'latitude', 'longitude', 'number_beers_x',
       'number_beers_y', 'phone', 'postal_code', 'state', 'street',
       'website_url'],
      dtype='object')

In [43]:
brewery_untapped_regional_df = pd.read_csv('untapped_regional.csv') 
brewery_untapped_regional_df = brewery_untapped_regional_df.drop(columns=['Unnamed: 0'])
brewery_untapped_regional_df

,brewery_name,brewery_location,brewery_type,number_beers,brewery_ratings
0,Tree House Brewing Company,"Charlton, MA United States",Regional Brewery,"842 Beers 4,172,821 Ratings",(4.336)
1,The Alchemist,"Stowe, VT United States",Regional Brewery,"112 Beers 728,071 Ratings",(4.332)
2,Trillium Brewing Company,"Canton, MA United States",Regional Brewery,"587 Beers 2,762,191 Ratings",(4.257)
3,Other Half Brewing Co.,"Brooklyn, NY United States",Regional Brewery,"1,600 Beers 3,941,845 Ratings",(4.227)
4,Equilibrium Brewery,"Middletown, NY United States",Regional Brewery,"598 Beers 1,455,948 Ratings",(4.202)
5,Russian River Brewing Company,"Windsor, CA United States",Regional Brewery,"175 Beers 1,302,667 Ratings",(4.174)
6,Great Notion Brewing,"Portland, OR United States",Regional Brewery,"718 Beers 858,910 Ratings",(4.156)
7,Toppling Goliath Brewing Co.,"Decorah, IA United States",Regional Brewery,"137 Beers 1,775,329 Ratings",(4.148)
8,Kane Brewing Company,"Ocean, NJ United States",Regional Brewery,"732 Beers 642,428 Ratings",(4.113)
9,Parish Brewing Co.,"Broussard, LA United States",Regional Brewery,"252 Beers 439,580 Ratings",(4.096)
10,Aslin Beer Company,"Alexandria, VA United States",Regional Brewery,"772 Beers 1,136,638 Ratings",(4.078)
11,Bearded Iris Brewing,"Nashville, TN United States",Regional Brewery,"343 Beers 586,698 Ratings",(4.076)
12,Old Nation Brewing Co.,"Williamston, MI United States",Regional Brewery,"232 Beers 425,033 Ratings",(4.075)
13,Prairie Artisan Ales,"Krebs, OK United States",Regional Brewery,"1,014 Beers 2,326,600 Ratings",(4.074)
14,The Bruery,"Placentia, CA United States",Regional Brewery,"598 Beers 2,015,308 Ratings",(4.071)
15,New England Brewing Co.,"Woodbridge, CT United States",Regional Brewery,"336 Beers 327,691 Ratings",(4.046)
16,Fiddlehead Brewing Company,"Shelburne, VT United States",Regional Brewery,"136 Beers 276,952 Ratings",(4.041)
17,Maine Beer Company,"Freeport, ME United States",Regional Brewery,"24 Beers 1,102,416 Ratings",(4.039)
18,Fremont Brewing,"Seattle, WA United States",Regional Brewery,"693 Beers 865,070 Ratings",(4.039)
19,Jackie O's Brewery,"Athens, OH United States",Regional Brewery,"360 Beers 900,674 Ratings",(4.037)
20,Wild Leap Brew Co.,"La Grange, GA United States",Regional Brewery,"87 Beers 190,996 Ratings",(4.022)
21,Untitled Art,"Waunakee, WI United States",Regional Brewery,"316 Beers 891,946 Ratings",(4.022)
22,Revision Brewing Company,"Sparks, NV United States",Regional Brewery,"246 Beers 511,146 Ratings",(4.016)
23,SingleCut Beersmiths,"Astoria, NY United States",Regional Brewery,"294 Beers 1,037,212 Ratings",(4.013)
24,Modern Times Beer,"San Diego, CA United States",Regional Brewery,"1,673 Beers 2,096,975 Ratings",(4.007)
25,Westbrook Brewing Co.,"Mt Pleasant, SC United States",Regional Brewery,"276 Beers 960,991 Ratings",(4.005)
26,3 Floyds Brewing,"Munster, IN United States",Regional Brewery,"424 Beers 2,537,776 Ratings",(4.002)
27,The Bruery Terreux,"Anaheim, CA United States",Regional Brewery,"337 Beers 675,893 Ratings",(3.996)
28,Creature Comforts Brewing Co.,"Athens, GA United States",Regional Brewery,"380 Beers 369,693 Ratings",(3.987)
29,Fort George Brewery,"Astoria, OR United States",Regional Brewery,"296 Beers 486,789 Ratings",(3.985)
30,Pinthouse Pizza,"Austin, TX United States",Regional Brewery,"952 Beers 244,092 Ratings",(3.985)
31,New Trail Brewing Co.,"Williamsport, PA United States",Regional Brewery,"281 Beers 575,762 Ratings",(3.974)
32,AleSmith Brewing Company,"San Diego, CA United States",Regional Brewery,"553 Beers 1,268,889 Ratings",(3.972)
33,Fieldwork® Brewing Company,"Berkeley, CA United States",Regional Brewery,"723 Beers 681,064 Ratings",(3.965)
34,Industrial Arts Brewing,"Beacon, NY United States",Regional Brewery,"90 Beers 277,331 Ratings",(3.965)
35,Maplewood Brewing Company,"Chicago, IL United States",Regional Brewery,"290 Beers 392,319 Ratings",(3.961)
36,Almanac,"Alameda, CA United States",Regional Brewery,"384 Beers 853,433 Ratings",(3.96)
37,Twelve5 Beverage Co.,"Neenah, WI United States",Regional Brewery,"27 Beers 18,009 Ratings",(3.953)
38,Sloop Brewing Co.,"Hopewell Junction, NY United States",Regional Brewery,"178 Beers 553,104 Ratings",(3.951)
39,Big Grove Brewery,"Iowa City, IA United States",Regional Brewery,"556 Beers 231,838 Ratings",(3.948)
40,La Cumbre Brewing Company,"Albuquerque, NM United States",Regional Brewery,"616 Beers 191,219 Ratings",(3.947)
41,Boneyard Beer,"Bend, OR United States",Regional Brewery,"269 Beers 254,996 Ratings",(3.94)
42,Firestone Walker Brewing Company,"Paso Robles, CA United States",Regional Brewery,"93 Beers 3,585,796 Ratings",(3.939)
43,Half Acre Beer Company,"Chicago, IL United States",Regional Brewery,"639 Beers 1,177,446 Ratings",(3.938)
44,Offshoot Beer Co.,"Placentia, CA United States",Regional Brewery,"85 Beers 219,345 Ratings",(3.935)
45,HenHouse Brewing Company,"Santa Rosa, CA United States",Regional Brewery,"262 Beers 176,088 Ratings",(3.929)
46,The Starkeller Brewery + Taproom,"New Ulm, MN United States",Regional Brewery,"43 Beers 41,578 Ratings",(3.928)
47,Alpine Beer Company,"Fort Collins, CO United States",Regional Brewery,"263 Beers 611,536 Ratings",(3.915)
48,Melvin Brewing,"Alpine, WY United States",Regional Brewery,"640 Beers 436,822 Ratings",(3.914)
49,Hardywood Park Craft Brewery,"Richmond, VA United States",Regional Brewery,"595 Beers 775,928 Ratings",(3.912)

In [45]:
#dfNew = merge(df, df2[cols_to_use], how='outer')

all_breweries_merged_df = pd.merge(all_breweries_merged_df[cols_to_use], brewery_untapped_regional_df, left_index=True, right_index=True,how="outer")
all_breweries_merged_df

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [ ]:
brewery_untapped_micro_df = pd.read_csv('untapped_micro.csv') 
brewery_untapped_micro_df

In [ ]:
all_breweries_merged_df = pd.merge(brewery_untapped_micro_df, all_breweries_merged_df, on=('brewery_name','brewery_type'), how='outer')

In [ ]:
all_breweries_merged_df

In [ ]:
all_breweries_merged_df.columns